folio-org/mod-patron

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
We now support version 5.0 of the circulation interface
> Updated the version for the circulation interface

- NEWS.md
- descriptors/ModuleDescriptor-template.json
This PR merely adds alternate dependencies on new interface versions for `holdings-storage` and `inventory`  (provided by recent, yet to be released, merges of mod-inventory-storage and mod-inventory)
> Consolidate 14 15

- pom.xml
- ramls/patron.raml
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- patron.raml updated to RAML1.0
- the resource implementation updated due to changes in the generated interface
- updated versions of some dependencies
> MODPATRON-13: upgrade to RAML1.0 and the latest RMB

- src/main/java/org/folio/rest/impl/HoldHelpers.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/HoldHelpersTest.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/hold_cancel.json
Fixed the CLOSED_CANCELED enum literal and date formatting when sending the PUT request to mod-circulation.
Had to refactor util methods for Holds into its own class in order to test the CLOSED_CANCELLED case.
> fixed bugs (enum and date formatting)

- NEWS.md
- pom.xml
PR for mod-patron v4.0.0 release.
> Tmp mod patron release 4.0.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/patron.raml
Updating news and version number
> updated News and updated version numbers

- pom.xml
Upgrade mod-patron to RMB v30.0.2 and aspectJ to v1.9.4.
My IDE just decides to make the whole file new again and I can't force it keeping the original spacing and such, and surprisingly in the IDE it only shows the differences in 2 expected lines.
> Upgrade mod-patron to RMB 30.0.2

- Dockerfile
- Jenkinsfile
- pom.xml
Resolves [MODPATRON-45](https://issues.folio.org/browse/MODPATRON-45)
> MODPATRON-45 Upgrade to RMB v31 and JDK 11

- descriptors/ModuleDescriptor-template.json
Resolves [MODPATRON-47](https://issues.folio.org/browse/MODPATRON-47)
> [MODPATRON-47] Update version of interface "feesfines" to v16.0

- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/instance_hold_bad_instance_id.json
- src/test/resources/PatronServicesResourceImpl/item_hold_bad_item_id.json
Respond with 422 error when same error is returned from circulation
> MODPATRON-31: The instance level request error handler can't map 422 errors

- ramls/patron.raml
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/java/org/folio/rest/impl/RequestTypeItemStatusWhiteListTests.java
https://issues.folio.org/browse/MODPATRON-100
- added limit min value in raml
- cannot add test due to validation for limit on raml level
Current response :
> MODPATRON-100 Inconsistent handling of invalid limit parameter

- NEWS.md
- pom.xml
> Tmp release 5.1.0

- NEWS.md
- pom.xml
> release 5.1.1

- NEWS.md
- pom.xml
- src/test/java/org/folio/integration/http/VertxOkapiHttpClientTest.java
I had some test failures in master that indicated a port binding problem.
This is why I've modified some of the test code-to have it bind to a dynamic 
port number, which usually solves the issue.
> MODPATRON-103: upgrading to RMB 33.2.4

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/HoldHelpers.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/hold_cancel_request_without_item.json
Resolves [MODPATRON-132](https://issues.folio.org/browse/MODPATRON-132)
> MODPATRON-132: Release v5.5.2 (Orchid 2023 R1 Bugfix)

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/Constants.java
- src/main/java/org/folio/rest/impl/HoldHelpers.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/RequestObjectFactory.java
- src/test/resources/PatronServicesResourceImpl/generic_hold_cancel_request.json
- src/test/resources/PatronServicesResourceImpl/hold_cancel.json
- src/test/resources/PatronServicesResourceImpl/hold_cancel_malformed.json
- src/test/resources/PatronServicesResourceImpl/hold_cancel_request.json
- src/test/resources/PatronServicesResourceImpl/hold_cancel_request_without_item.json
- src/test/resources/PatronServicesResourceImpl/hold_cancel_without_cancel_date.json
- src/test/resources/PatronServicesResourceImpl/holds_all_active.json
- src/test/resources/PatronServicesResourceImpl/holds_all_active_and_sorted.json
- src/test/resources/PatronServicesResourceImpl/holds_create.json
- src/test/resources/PatronServicesResourceImpl/holds_one_invalid_status.json
- src/test/resources/PatronServicesResourceImpl/holds_one_record.json
- src/test/resources/PatronServicesResourceImpl/instance_holds_create.json
- src/test/resources/PatronServicesResourceImpl/instance_holds_tlr_create.json
- src/test/resources/PatronServicesResourceImpl/page_create.json
Changing spelling of parameter to match spelling in CIRC-253: https://issues.folio.org/browse/CIRC-253
> MODPATRON-137: change spelling of parameter

- Dockerfile
- Jenkinsfile
- pom.xml
Resolves [MODPATRON-146](https://issues.folio.org/browse/MODPATRON-146)
> MODPATRON-146: Move to Java 17

- descriptors/ModuleDescriptor-template.json
MODPATRON-147
Add patron.hold.allowed-service-points.get permission to patron.all
> MODPATRON-147 Add allowed SP permission

- NEWS.md
- pom.xml
Resolves: [MODPATRON-148](https://issues.folio.org/browse/MODPATRON-148)
> [MODPATRON-148] Release v6.0.0

- NEWS.md
- pom.xml
Resolves: [MODPATRON-163](https://folio-org.atlassian.net/browse/MODPATRON-163)
> [MODPATRON-163] Release v6.1.0

- descriptors/ModuleDescriptor-template.json
- ramls/examples/external_patron_collection.json
- ramls/external_patron_collection.json
- ramls/patron.raml
- src/main/java/org/folio/patron/rest/models/UsersCollection.java
- src/main/java/org/folio/patron/rest/utils/PatronUtils.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/UserRepository.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/external_user7.json
https://folio-org.atlassian.net/browse/MODPATRON-169
> [MODPATRON-169]-Added GET endpoint for expired LC users

- descriptors/ModuleDescriptor-template.json
- ramls/patron.raml
- src/main/java/org/folio/patron/rest/models/User.java
- src/main/java/org/folio/patron/rest/utils/PatronUtils.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/UserRepository.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
https://folio-org.atlassian.net/browse/MODPATRON-170
> [MODPATRON-170]-Fix vulnerabilities

- src/main/java/org/folio/patron/rest/utils/PatronUtils.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/UserRepository.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/remote_patron6.json
- src/test/resources/PatronServicesResourceImpl/remote_patron7.json
https://folio-org.atlassian.net/browse/MODPATRON-173
> [MODPATRON-173]-Fix vulnerabilities

- ramls/examples/external_patron_collection.json
- ramls/external_patron.json
https://folio-org.atlassian.net/browse/MODPATRON-177
> MODPATRON-177: fixed PreferredEmailCommunication SERVICE to SERVICES

- ramls/patron.raml
- src/main/java/org/folio/patron/rest/models/ExternalPatronErrorCode.java
- src/main/java/org/folio/patron/rest/models/User.java
- src/main/java/org/folio/patron/rest/utils/PatronUtils.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/patron/rest/utils/PatronUtilsTest.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/remote_patron_multiple_users.json
https://folio-org.atlassian.net/browse/MODPATRON-179
> MODPATRON-179: Enhance the error response to ENUM constant for LC User registration APIs

- src/main/java/org/folio/patron/rest/models/User.java
- src/main/java/org/folio/rest/impl/UserRepository.java
https://folio-org.atlassian.net/browse/MODPATRON-180
> MODPATRON-180: [LC API] Fixed Enrolment Date field is not saving in database

- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
https://folio-org.atlassian.net/browse/MODPATRON-182
> MODPATRON-182: added debugging logs for getPatronAccountById API

- src/main/java/org/folio/rest/impl/UrlPath.java
- src/test/java/org/folio/rest/impl/AllowedServicePointPathTest.java
[MODPATRON-178](https://folio-org.atlassian.net/browse/MODPATRON-178)
> MODPATRON-178: Fix mod-circulation-bff's allowed-service-points URL 

- descriptors/ModuleDescriptor-template.json
- ramls/examples/user.json
- ramls/patron.raml
- ramls/userdata.json
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/UserRepository.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/user_active1.json
- src/test/resources/PatronServicesResourceImpl/user_multiple.json
- src/test/resources/PatronServicesResourceImpl/user_not_active1.json
- src/test/resources/PatronServicesResourceImpl/user_not_found.json
**Purpose**
The purpose of the PR is to implement [MODPATRON-190](https://folio-org.atlassian.net/browse/MODPATRON-190)
> MODPATRON-190 Modify existing getByEmail API to return patron details as per new design

- pom.xml
Resolves: [MODPATRON-189](https://folio-org.atlassian.net/browse/MODPATRON-189)
> [MODPATRON-189] Update to RMB 35.3.0

- NEWS.md
- pom.xml
Resolves: [MODPATRON-187](https://folio-org.atlassian.net/browse/MODPATRON-187)
> [MODPATRON-187] Release 6.2.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/CirculationRequestService.java
- src/main/java/org/folio/rest/impl/EcsTlrSettingsService.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/RequestContext.java
- src/main/java/org/folio/rest/impl/RequestObjectFactory.java
- src/main/java/org/folio/rest/impl/UrlPath.java
- src/test/java/org/folio/rest/impl/AllowedServicePointPathTest.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/primaryEcsTlrRequest_itemLevel_hold.json
- src/test/resources/PatronServicesResourceImpl/primaryEcsTlrRequest_itemLevel_page.json
- src/test/resources/PatronServicesResourceImpl/primaryEcsTlrRequest_titleLevel_page.json
Resolves: [MODPATRON-195](https://folio-org.atlassian.net/browse/MODPATRON-195)
> MODPATRON-195 Release 6.2.1

- src/main/java/org/folio/integration/http/VertxOkapiHttpClient.java
- src/main/java/org/folio/rest/impl/CirculationRequestService.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
ECS TLR creation fails with 5000ms timeout on BugFest
Increase timeout
> MODPATRON-197 Create requests with 20s timeout

- ramls/examples/staging_user.sample
- ramls/patron.raml
- ramls/staging_userdata.json
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/staging-users-post-response.json
Changes made to add externalSystemId in the staging-user json files and POST /staging-users api will be used to only create a new staging user.
> MODPATRON-198 - Changes for the external system id in staging users.

- NEWS.md
- pom.xml
- src/main/java/org/folio/integration/http/VertxOkapiHttpClient.java
- src/main/java/org/folio/rest/impl/CirculationRequestService.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
Resolves: [MODPATRON-199](https://folio-org.atlassian.net/browse/MODPATRON-199)
> MODPATRON-199 Release 6.2.3

- src/main/java/org/folio/integration/http/VertxOkapiHttpClient.java
Resolves: [MODPATRON-197](https://folio-org.atlassian.net/browse/MODPATRON-197)
> MOPATRON-197 Modify the timeout value for the request creation chain invocation

- NEWS.md
- pom.xml
- src/main/java/org/folio/integration/http/VertxOkapiHttpClient.java
Resolves: [MODPATRON-204](https://folio-org.atlassian.net/browse/MODPATRON-204)
> MODPATRON-204 Release 6.2.4

- descriptors/ModuleDescriptor-template.json
MODPATRON-208
Add missing required interfaces
> MODPATRON-208 Add missing required interfaces

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Resolves: [MODPATRON-210](https://folio-org.atlassian.net/browse/MODPATRON-210)
> MODPATRON-210 Release 6.2.6

- NEWS.md
- pom.xml
- src/main/java/org/folio/integration/http/ResponseInterpreter.java
- src/main/java/org/folio/rest/impl/EcsTlrSettingsService.java
Resolves: [MODPATRON-221](https://folio-org.atlassian.net/browse/MODPATRON-221)
> MODPATRON-221 Release 6.2.8

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/CirculationRequestService.java
- src/main/java/org/folio/rest/impl/RequestObjectFactory.java
- src/main/java/org/folio/rest/impl/UrlPath.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
[MODPATRON-212](https://folio-org.atlassian.net/browse/MODPATRON-212)
> MODPATRON-212: Delegate creation of mediated requests to mod-circulation-bff

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/CirculationRequestService.java
- src/main/java/org/folio/rest/impl/RequestObjectFactory.java
- src/main/java/org/folio/rest/impl/UrlPath.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
Resolves: [MODPATRON-222](https://folio-org.atlassian.net/browse/MODPATRON-222)
> MODPATRON-222 Release 6.2.9

- Dockerfile
- Jenkinsfile
- pom.xml
https://folio-org.atlassian.net/browse/MODPATRON-223
- updated required files
- update dependencies
> [MODPATRON-223] - Update to mod-patron Java 21

- NEWS.md
- pom.xml
Resolves: [MODPATRON-224](https://folio-org.atlassian.net/browse/MODPATRON-224)
> MODPATRON-224 Release 6.3.0

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODPATRON-225
Fix interface dependency
> MODPATRON-225 Fix circulation-bff-request-external interface dependency

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
https://folio-org.atlassian.net/browse/MODPATRON-226
> MODPATRON-226: Release 6.2.10 (Ramsons R2 2024 CSP #1)

- descriptors/ModuleDescriptor-template.json
Add missing permission to update staging user.
[MODPATRON-230](https://folio-org.atlassian.net/browse/MODPATRON-230)
> MODPATRON-230: Add missing permission

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODPATRON-229
> MODPATRON-229: Add missing dependency on holdings storage

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODPATRON-231](https://folio-org.atlassian.net/browse/MODPATRON-231)
> MODPATRON-231: Release v6.2.11

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODPATRON-232](https://folio-org.atlassian.net/browse/MODPATRON-232)
> MODPATRON-232: Release 6.3.1

- descriptors/ModuleDescriptor-template.json
- ramls/allowed-service-point.json
- ramls/examples/allowed-service-points-response.json
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/resources/PatronServicesResourceImpl/allowed_service_points_circulation.json
- src/test/resources/PatronServicesResourceImpl/allowed_service_points_circulation_bff.json
- src/test/resources/PatronServicesResourceImpl/allowed_service_points_circulation_bff_response.json
- src/test/resources/PatronServicesResourceImpl/allowed_service_points_circulation_response.json
- src/test/resources/PatronServicesResourceImpl/allowed_sp_mod_circulation_response.json
- src/test/resources/PatronServicesResourceImpl/allowed_sp_mod_patron_expected.json
- src/test/resources/PatronServicesResourceImpl/allowed_sp_mod_patron_expected_response.json
https://folio-org.atlassian.net/browse/MODPATRON-233
> MODPATRON-233: Added discoveryDisplayName in item and instance AllowedServicePoint response

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/allowed-service-point.json
- ramls/examples/allowed-service-points-response.json
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/resources/PatronServicesResourceImpl/allowed_service_points_circulation.json
- src/test/resources/PatronServicesResourceImpl/allowed_service_points_circulation_bff.json
- src/test/resources/PatronServicesResourceImpl/allowed_service_points_circulation_bff_response.json
- src/test/resources/PatronServicesResourceImpl/allowed_service_points_circulation_response.json
- src/test/resources/PatronServicesResourceImpl/allowed_sp_mod_circulation_response.json
- src/test/resources/PatronServicesResourceImpl/allowed_sp_mod_patron_expected.json
- src/test/resources/PatronServicesResourceImpl/allowed_sp_mod_patron_expected_response.json
https://folio-org.atlassian.net/browse/MODPATRON-234
> Ramsons (CSP#3) release 6.2.12

- NEWS.md
- PULL_REQUEST_TEMPLATE.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/staging_userdata.json
- src/test/resources/PatronServicesResourceImpl/renew_create.json
- src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdItemByItemIdRenew.json
- src/test/resources/PatronServicesResourceImpl/staging-users-post-request.json
- src/test/resources/PatronServicesResourceImpl/staging-users-post-response.json
https://folio-org.atlassian.net/browse/MODPATRON-245
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to …
> Sunflower release 6.3.2
