folio-org/mod-patron

- README.md
- pom.xml
Now that there is a mod-patron JIRA project, we can update the links in the project. Fixes MODPATRON-1.
> Update the issue tracker link

- NEWS.md
- descriptors/ModuleDescriptor-template.json
It is not clear why the interface version has been updated to 15.0, perhaps to match the package version? Whatever the reason, the APIs and JSON schemas mod-patron uses have not changed in many months.
> Update the feesfines interface version (MODPATRON-16)

- descriptors/ModuleDescriptor-template.json
As it does not use the rules related endpoints changed in version 6.0
> Include 6.0 in supported circulation versions MODPATRON-17

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/examples/hold.json
- ramls/hold.json
- ramls/patron.raml
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/holds_all.json
- src/test/resources/PatronServicesResourceImpl/holds_create.json
- src/test/resources/PatronServicesResourceImpl/holds_create_bad_data.json
- src/test/resources/PatronServicesResourceImpl/request_testPostPatronAccountByIdItemByItemIdHold.json
- src/test/resources/PatronServicesResourceImpl/response_testGetPatronAccountById.json
- src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdItemByItemIdHold.json
Updated the `circulation` interface dependency to 7.0, which introduces breaking changes to the `requestExpriationDate` which mod-patron passes on as `expirationDate` in the `hold` schema. The change includes a time component to the date. Since it is a breaking change for mod-patron users, the `patron` interface has been updated to 2.0.
> MODPATRON-18 - support circulation 7.0

- ramls/examples/account.json
- ramls/examples/hold.json
- ramls/hold.json
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/holds_all.json
- src/test/resources/PatronServicesResourceImpl/holds_create.json
- src/test/resources/PatronServicesResourceImpl/instance_holds_create.json
- src/test/resources/PatronServicesResourceImpl/response_testGetPatronAccountById.json
- src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdInstanceByInstanceIdHold.json
- src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdItemByItemIdHold.json
When returning the request details in a patron account request or hold request, we now return the request queue position.
Also, the "requestLength" JSON field was removed as it is not necessary at this time and probably never will be.
Finally, altered the FOLIO request query to return all requests, not just holds. This way, the client will be able to see page and recalls as well, though the client (a discovery service) will not be able to distinguish between the request types.
> MODPATRON-2: add request queue position to the hold (request)

- ramls/hold.json
This is a temporary measure in order to integrate with a currently deployed discovery service.
> MODPATRON-25: remove some validation restrictions

- src/main/java/org/folio/rest/impl/Constants.java
- src/main/java/org/folio/rest/impl/ItemStatus.java
- src/main/java/org/folio/rest/impl/LookupsUtils.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/RequestObjectFactory.java
- src/main/java/org/folio/rest/impl/RequestPolicy.java
- src/main/java/org/folio/rest/impl/RequestType.java
- src/main/java/org/folio/rest/impl/RequestTypeItemStatusWhiteList.java
- src/main/java/org/folio/rest/impl/RequestTypeParameters.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/java/org/folio/rest/impl/RequestTypeItemStatusWhiteListTests.java
- src/test/resources/PatronServicesResourceImpl/holds_create.json
- src/test/resources/PatronServicesResourceImpl/item_book4.json
- src/test/resources/PatronServicesResourceImpl/item_checkedout.json
- src/test/resources/PatronServicesResourceImpl/item_intransit.json
- src/test/resources/PatronServicesResourceImpl/page_create.json
- src/test/resources/PatronServicesResourceImpl/requestPolicyId_all.json
- src/test/resources/PatronServicesResourceImpl/requestPolicyId_hold.json
- src/test/resources/PatronServicesResourceImpl/requestPolicyId_page.json
- src/test/resources/PatronServicesResourceImpl/requestPolicy_all.json
- src/test/resources/PatronServicesResourceImpl/requestPolicy_hold.json
- src/test/resources/PatronServicesResourceImpl/requestPolicy_page.json
- src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdItemByItemIdPage.json
- src/test/resources/PatronServicesResourceImpl/user_active.json
- Implemented the logic to determine request type based on a tenant's request policy and white list.
- Borrowed code for white list, requestType, itemStatus, request policy from mod-circulation.
-  Essentially, it gets a list of allowed request types from the request policy, and checks the types with the item status against the white list.  When it finds a first allowable request type and item status combination, it will use that request type.  When it cannot find an appropriate request type to make a request, it returns an error with the message "Cannot find a valid request type for this item".
Refactored the code as follows:
- Created a new RequestObjectFactory class that handles creating item-level request objects.  In the future we could migrate instance-level object requests creation …
> MODPATRON-26

- Dockerfile
- descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
> MODPATRON-35 FOLIO-2358 manage container memory

- pom.xml
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
1. Set the request's status to Closed - Cancelled.  A PUT to /mod-circulation doesn't automatically set the request's status, have to explicitly set it.
2. Send to mod-circulation a Request object instead of a Hold object.  Request and Hold objects are similar, but not the same. Use the Request object that was obtained from the GET as a base to which the cancellation fields' values are updated and finally sent to mod-circulation.
> Fixed bugs in cancelling requests

- descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODPATRON-36: Migrate to new major version of item-storage, inventory, circulation.
Changes:
Changes:
1. `item.status.name` has restricted to the following values:
* Available
* Awaiting pickup
* Awaiting delivery
* Checked out
* In process
* In transit
* Missing
* On order
* Paged
* Withdrawn
* Declared lost
2. *Item.status* and *item.status.name* are required now, no defaulting available anymore;
3. Array *item.copyNumbers* converted to a single value *copyNumber*;
4. Item.status.date is read-only field now and has date-time formatting now ("yyyy-MM-dd'T'HH:mm:ss.SSS+0000").
1. Array *request.item.copyNumbers* has converted to a single value - *copyNumber*;
2. *request/loan.item.status.date* has date-time formatting.
**Have to be merged with** …
> MODPATRON-36: Migrate to item-storage 8.0 and inventory 10.0.

- NEWS.md
- descriptors/ModuleDescriptor-template.json
Add support for `circulation` `v10.0`. The important difference from `v9.5` is
the removal of the `override-checkout-by-barcode` endpoint which is not
used here.
Refs [MODPATRON-52](https://issues.folio.org/browse/MODPATRON-52)
> MODPATRON-52 support circulation v10.0

- descriptors/ModuleDescriptor-template.json
Resolves [MODPATRON-54](https://issues.folio.org/browse/MODPATRON-54).
There is a breaking change in `mod-circulaion` that will be merge soon. Modules that have a dependency on `circulation` interface need to be updated to support version `11.0`.
There are multiple PRs with `circulation` interface version update, they all should be merged on the same day. 
**DO NOT MERGE** this PR until then.
> MODPATRON-54 Update circulation interface version

- NEWS.md
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/accounts_all.json
- src/test/resources/PatronServicesResourceImpl/feefine_no_item.json
- src/test/resources/PatronServicesResourceImpl/response_testGetPatronAccountById.json
Traced this problem to code in getPatronAccountById method of 
PatronServicesResourceImpl class.  The code had been written in such
a way that it expected every charge to have item data attached.  When
there was none, the code would assign a null value to the item Id field, then
when that object got passed to the item lookup function, a search for data
on that item would result in an error which got pushed up to the API endpoint.
I rewrote the code to skip item lookup for charges with no item data.  I also 
adjusted the test on this endpoint to include an account with no item data.
I also noticed that the endpoint does not seem to supply feeFine identifiers
for charges, yet the test file used for comparison had that data in the 
expected response-even though none of the tests checked for …
> MODPATRON-59: Account lookup fails if patron has fees/fines without item info

- NEWS.md
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/accounts_all.json
The data returned from the accounts endpoint to mod-patron
does not have a "dateCreated" field at the top level.  Perhaps 
it once did and at some point the schema changed?  In any case,
the code needs to be looking for this information in the 
"metadata" jsonobject. If it does not find data where it expects, 
it looks like a later process fills in the field with the current date 
and time. The tests did not pick up on this because 
they work from a static template, and the data in that template was 
structured with the fields they expected to see.  I changed that template
to put the data where the accounts endpoint actually puts it.
> MODPATRON-62: Account lookup returns wrong accrual date for fines/fees

- NEWS.md
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/RequestObjectFactory.java
- src/test/resources/PatronServicesResourceImpl/request_testPostPatronAccountByIdInstanceByInstanceIdHold.json
- src/test/resources/PatronServicesResourceImpl/request_testPostPatronAccountByIdItemByItemIdHold.json
- Fixes [https://issues.folio.org/browse/MODPATRON-61](https://issues.folio.org/browse/MODPATRON-61)
- Unit test already exists, but needed sample data updated to properly validate `patronComments` field. See: https://github.com/folio-org/mod-patron/blob/b013017dda56d8e5a5627039a92fcf66091522a0/src/test/java/org/folio/rest/impl/PatronResourceImplTest.java#L825
> Corrected missing reference for patronComments when placing PUT request

- pom.xml
- src/main/java/org/folio/rest/impl/LookupsUtils.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/RequestObjectFactory.java
- src/test/java/org/folio/rest/impl/HoldHelpersTest.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/response_testGetPatronAccountById.json
- src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdItemByItemIdRenew.json
Upgraded to RMB 33.x, vertx 4.1.x, and removed deprecated classes.
Significant changes to the LookupsUtils class were required to move to the vertx WebClient and the tests were impacted by several changes introduced by both the new version of RMB and the introduction of the WebClient.
> Modpatron 53

- pom.xml
Code coverage reporting on mod-patron has been broken since [February](https://github.com/folio-org/mod-patron/commit/4d86a6efbb30598e8cec023fed4a12cc5f8ee8c8).
This was caused by stopping any additional arguments being provided to the surefire plugin, which stops Jacoco from generating coverage to then be picked up by Sonar.
> Fix code coverage reporting MODPATRON-66

- pom.xml
- src/main/java/org/folio/integration/http/HttpClientFactory.java
- src/main/java/org/folio/integration/http/Response.java
- src/main/java/org/folio/integration/http/ResponseInterpreter.java
- src/main/java/org/folio/integration/http/VertxOkapiHttpClient.java
- src/main/java/org/folio/rest/impl/ItemRepository.java
- src/main/java/org/folio/rest/impl/LookupsUtils.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/RequestObjectFactory.java
- src/main/java/org/folio/rest/impl/UserRepository.java
- src/test/java/org/folio/integration/http/VertxOkapiHttpClientTest.java
When [multiple web clients](https://vertx.io/docs/vertx-web-client/java/) are used they can produce memory leak like symptoms and the module can fail to take advantage of connection pooling.
In anticipation of those kinds of things being reported, this change is intended so that only a single web client is used within mod-patron.
This was considered outside of scope of the original Vert.x 4.0 upgrade work that moved the module to use web client.
In order to achieve this, the code was refactored so that all HTTP requests are made using the same client class (rather than in utility classes or other parts of the code).
This also involved introducing a factory that means that only a single WebClient is created per instance of Vert.x
Usually there would only be a single instance in production, …
> Use a single web client MODPATRON-66

- pom.xml
Logging is broken in recent versions of this module.
See https://issues.folio.org/browse/MODPATRON-70 for details
* Move the Log4j2Plugins.dat exclusion in the maven shade plugin to the appropriate place in pom.xml
* Not required, but update the version of the maven-shade-plugin (3.2.1 -> 3.2.4)
https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-310
> MODPATRON-70 fix logging

- descriptors/ModuleDescriptor-template.json
I added the relevant permission to the base endpoint.
> MODPATRON-77:  Fee/Fines information is not returned due to a missing permission

- README.md
- ramls/patron.raml
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/accounts_all_active_and_sorted.json
- src/test/resources/PatronServicesResourceImpl/holds_all_active_and_sorted.json
- src/test/resources/PatronServicesResourceImpl/loans_all_active_and_sorted.json
- src/test/resources/PatronServicesResourceImpl/response_testGetPatronAccountById_sortedByItemTitle.json
https://issues.folio.org/browse/MODPATRON-79
Add new sortBy parameter for GET /patron/account/{id} endpoint to support for sorting the lists of {holds, loans, charges} in  account info responses. 
1) Update GET /patron/account/{id} endpoint in patron.raml with sortBy query parameter
2) Update PatronServicesResourceImpl to append sortBy value to query CQL expression when retrieve loans (GET /circulation/loans), charges (GET /accounts) and holds (GET /circulation/requests)
3) Update unit tests
> MODPATRON-79 Add sorting of patron account info

- ramls/patron.raml
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/accounts_one_record.json
- src/test/resources/PatronServicesResourceImpl/accounts_total.json
- src/test/resources/PatronServicesResourceImpl/holds_one_record.json
- src/test/resources/PatronServicesResourceImpl/loans_one_record.json
- src/test/resources/PatronServicesResourceImpl/response_testGetPatronAccountByIdByLimitAndOffset.json
https://issues.folio.org/browse/MODPATRON-j80
Introduce new query paramters "limit" and "offset" for GET /patron/account/{id} endpoint to support paging the lists of {holds, loans, charges} in  account info responses. 
1) Update GET /patron/account/{id} endpoint in patron.raml with "limit" and "offset" query parameter
2) Update PatronServicesResourceImpl to append limit and offset when retrieve loans (GET /circulation/loans), charges (GET /accounts) and holds (GET /circulation/requests) by next logic:
1. If includeItem is false, set limit=0, regardless of whether limit was provided in the incoming request or not.
2. else
a) If limit was specified on the incoming request, use this value and include offset if it was specified.
b) else, use Integer.MAX_VALUE.
3) Update unit tests
> MODPATRON-80 Support paging of patron account info

- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
In case if the /patron/account is called and includeCharges param equal false we still should get all charges to calculate charges "amount" to add this information to "chargesTotal.amount". 
Update getAccount() in PatronServicesResourceImpl class to always pass value "true" instead of includeCharges variable to getLimitAndOffset method. In this case, limit value is set from limit param if it presents, otherwise, Integer.MAX_VALUE value is set
> Fix limit for charges when includeCharges equals false

- NEWS.md
- pom.xml
Resolve CVE-2021-44228 as per [MODPATRON-94](https://issues.folio.org/browse/MODPATRON-94).
> MODPATRON-94: Upgrade to RMB 33.0.4 and Log4J to 2.16.0 (Kiwi R3 2021).

- NEWS.md
- pom.xml
Resolve CVE-2021-44228 as per [MODPATRON-96](https://issues.folio.org/browse/MODPATRON-96).
> MODPATRON-96: Upgrade to RMB 32.2.4 and Log4J to 2.16.0 (Juniper R2 2021).

- NEWS.md
- pom.xml
Resolve CVE-2021-44228 as per [MODPATRON-94](https://issues.folio.org/browse/MODPATRON-94).
> MODPATRON-94: Upgrade to RMB 33.0.4 and Log4J to 2.16.0 (Lotus)

- descriptors/ModuleDescriptor-template.json
Adapt the module to changed interface of mod-circulation from v12.0 to v13.0
Adapt ModuleDescriptor-template to circulation interface v13.0;
https://issues.folio.org/browse/MODPATRON-101
> MODPATRON-101 Support circulation interface v13

- Jenkinsfile
- README.md
- ramls/account.json
- ramls/money.json
- ramls/patron.raml
[MODPATRON-110](https://issues.folio.org/browse/MODPATRON-110)
[FOLIO-3231](https://issues.folio.org/browse/FOLIO-3231)
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
> MODPATRON-110 Use new api-lint and api-doc CI facilities

- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/instance_holds_tlr_create.json
- src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdInstanceByInstanceIdHoldNoItemId.json
Resolves: https://issues.folio.org/browse/MODPATRON-104.
When attempting to create a request via edge/mod-patron using the /patron/account/<patronId>/instance/<instanceId>/hold endpoint with TLR enabled, a true title-level request should be created (requestLevel="Title"). Instead, every request made via this endpoint results in an item-level request (TLR-lite).
The main fix is expected to be in mod-circulation, but a test should be added in mod-patron for how it behaves if it recieves TLR without item.
> MODPATRON-104 Do not pass request level to mod-circulation when creating instance request

- NEWS.md
- src/main/java/org/folio/integration/http/VertxOkapiHttpClient.java
- src/test/java/org/folio/integration/http/VertxOkapiHttpClientTest.java
I replicated the original circumstances that caused EDGPATRON-97, the issue that
spawned this one.  What I discovered is that when an account has an invalid paymentStatus,
Any request for that account results in the request to mod-feesfines effectively never terminating.
So I set timeout limits on HttpClients within mod-patron.  Please let me know if 
you think the timeout should be longer/shorter than 5 seconds.  This results in mod-patron returning
a 500 error with a full description of the timeout error, including the endpoint and parameters of the 
failed request, if the request times out.  I tested this by running both modules locally, and forcing 
mod-patron to request account data from the local instance of mod-feesfines for the faulty account data.
> MODPATRON-119: Improve error logging and response in mod-patron

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODPATRON-122
Incidental problems also fixed:
- Incorrect NEWS.md data.
- Explicit Junit version (4.13.1) pulled in and is an older version than the already provided Junit managed version (5.7.0).
> MODPATRON-122: Upgrade to RAML Module Builder 35.x.x.

- descriptors/ModuleDescriptor-template.json
Testing revealed that the endpoint need an additional permission to search the configuration endpoint.  I'm adding it here.
> MODPATRON-7: adding additional permission to patron endpoint

- src/main/java/org/folio/rest/impl/HoldHelpers.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/hold_cancel_request_without_item.json
- Fix cancelling TLR that were created without items returns HTTP 500
Resolves: [MODPATRON-131](https://issues.folio.org/browse/MODPATRON-131)
- Fix NPE for cancelling request without item;
- Fix doubling response error handling; 
- Add test to cover the scenario
> MODPATRON-131 Cancelling TLRs that were created without items returns HTTP 500

- descriptors/ModuleDescriptor-template.json
It does not look as though there are any modifications that need to be made to the actual module
code to support the change.  My understanding is that we always make version numbers inclusive if possible, 
so I've added it to the list of supported versions rather than replacing anything.
> MODPATRON-133: updating feefine interface to 18.0

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- README.md
- ramls/patron.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 MODPATRON-139 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- descriptors/ModuleDescriptor-template.json
- ramls/allowed-service-point.json
- ramls/allowed-service-points-response.json
- ramls/examples/allowed-service-points-response.json
- ramls/patron.raml
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/allowed_service_points_instance_not_found.json
- src/test/resources/PatronServicesResourceImpl/allowed_sp_mod_circulation_response.json
- src/test/resources/PatronServicesResourceImpl/allowed_sp_mod_patron_expected_response.json
[MODPATRON-147](https://issues.folio.org/browse/MODPATRON-147)
Discovery application need to know which service points are available as pickup locations.
Reusing existing mod-circulation's endpoint and combining the result into a single list of service points (because they can't choose the request type on the discovery side).
> MODPATRON-147 Add allowed-service-points endpoint

- pom.xml
Covers: [MODPATRON-160](https://folio-org.atlassian.net/browse/MODPATRON-160)
Upgrade to RMB 35.2.0, Vertx 4.5.5, Spring 6.1.5
> MODPATRON-160 Upgrade to RMB 35.2.0, Vertx 4.5.5

- descriptors/ModuleDescriptor-template.json
- ramls/examples/external_patron.json
- ramls/external_patron.json
- ramls/patron.raml
- src/main/java/org/folio/patron/rest/models/User.java
- src/main/java/org/folio/patron/rest/utils/PatronUtils.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/UserRepository.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/addressTypes.json
- src/test/resources/PatronServicesResourceImpl/external_user.json
- src/test/resources/PatronServicesResourceImpl/external_user2.json
- src/test/resources/PatronServicesResourceImpl/external_user3.json
- src/test/resources/PatronServicesResourceImpl/external_user4.json
- src/test/resources/PatronServicesResourceImpl/external_user5.json
- src/test/resources/PatronServicesResourceImpl/group.json
- src/test/resources/PatronServicesResourceImpl/remote_patron.json
- src/test/resources/PatronServicesResourceImpl/remote_patron2.json
- src/test/resources/PatronServicesResourceImpl/remote_patron3.json
- src/test/resources/PatronServicesResourceImpl/remote_patron4.json
- src/test/resources/PatronServicesResourceImpl/remote_patron5.json
https://folio-org.atlassian.net/browse/MODPATRON-166.
Approach:- In scope of this PR we are creating user based on LOC application requirement .
> [MODPATRON-165]-Added POST api for external patron.

- src/main/java/org/folio/rest/impl/EcsTlrSettingsService.java
- src/test/java/org/folio/rest/impl/AllowedServicePointPathTest.java
Purpose:
Create URL routing between mod-circulation and mod-circulation-bff depends on ecsTlrFeatureEnabled value when "allowed service points" endpoint executed.
Jira ticket:
[MODPATRON-178](https://folio-org.atlassian.net/browse/MODPATRON-178)
> MODPATRON-178: Fixed exception handling

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/hold.json
- src/main/java/org/folio/rest/impl/CirculationRequestService.java
- src/main/java/org/folio/rest/impl/PatronServicesResourceImpl.java
- src/main/java/org/folio/rest/impl/UrlPath.java
- src/test/java/org/folio/rest/impl/PatronResourceImplTest.java
- src/test/resources/PatronServicesResourceImpl/mediatedRequest_itemLevel_hold.json
- src/test/resources/PatronServicesResourceImpl/mediatedRequest_itemLevel_hold_response.json
- src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdItemByItemIdHoldMedRequest.json
Locate should be able to create mediated requests in the secure tenant. Chain of calls:
mod-patron (secure tenant) → mod-requests-mediated (same tenant, secure)
Check if we’re in the secure tenant (use env var SECURE_TENANT_ID)
If we are, create a mediated request in mod-requests-mediated instead of a regular request in mod-circulation
Resolves: [MODPATRON-194](https://folio-org.atlassian.net/browse/MODPATRON-194)
> MODPATRON-194 Create mediated requests in secure tenant

- src/main/java/org/folio/integration/http/ResponseInterpreter.java
- src/main/java/org/folio/rest/impl/EcsTlrSettingsService.java
Fix IndexOutOfBounds exception that occurs when processing the feature toggle during the call to the 'circulation-settings-storage/circulation-settings' endpoint on single tenant environment
Resolves: [MODPATRON-219](https://folio-org.atlassian.net/browse/MODPATRON-219)
> MODPATRON-219 Fix IndexOutOfBounds exception for single tenant environment

- descriptors/ModuleDescriptor-template.json
Fix incorrect required interface name: `circulation-bff-request-external` -> `circulation-bff-ecs-request-external`.
[MODPATRON-229](https://folio-org.atlassian.net/browse/MODPATRON-229)
> MODPATRON-229: Fix required interface name
